-- 1. Tabele copil (depind de altele)
DROP TABLE Internship CASCADE CONSTRAINTS;
DROP TABLE Dive_Crew CASCADE CONSTRAINTS;
DROP TABLE Itinerary_Segment CASCADE CONSTRAINTS;

-- 2. Tabele intermediare
DROP TABLE Scheduled_Dive CASCADE CONSTRAINTS;
DROP TABLE Route CASCADE CONSTRAINTS;

-- 3. Tabele principale
DROP TABLE Itinerary CASCADE CONSTRAINTS;
DROP TABLE Passenger CASCADE CONSTRAINTS;

-- 4. Tabele Crew
DROP TABLE Medic CASCADE CONSTRAINTS;
DROP TABLE Engineer CASCADE CONSTRAINTS;
DROP TABLE Captain CASCADE CONSTRAINTS;
DROP TABLE Crew_Member CASCADE CONSTRAINTS;

-- 5. Tabele independente
DROP TABLE Station CASCADE CONSTRAINTS;
DROP TABLE Submarine_Type CASCADE CONSTRAINTS;
