CREATE USER octavian IDENTIFIED BY Octavian2005;
GRANT CONNECT, RESOURCE TO octavian;
ALTER USER octavian QUOTA UNLIMITED ON USERS;

CREATE USER cerinte_plsql IDENTIFIED BY cerinte_plsql;
GRANT CONNECT, RESOURCE TO cerinte_plsql;
ALTER USER cerinte_plsql QUOTA UNLIMITED ON USERS;  


CREATE USER tema_1 IDENTIFIED BY tema_1;
GRANT CONNECT, RESOURCE TO tema_1;
ALTER USER tema_1 QUOTA UNLIMITED ON USERS; 