CREATE TABLE produse (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100),
    pret NUMBER(10,2),
    stoc NUMBER
);

INSERT INTO produse (nume, pret, stoc) VALUES ('Laptop Lenovo', 3500, 10);
INSERT INTO produse (nume, pret, stoc) VALUES ('Mouse Logitech', 120, 50);
INSERT INTO produse (nume, pret, stoc) VALUES ('Monitor Dell', 900, 20);

COMMIT;
